baseURL = "https://clinicalbrainlab.github.io/"
languageCode = "en-us"
title = "The Clinical Brain Lab"
theme = "hugo-initio"
publishDir = "public"

[params]
    name = "Clinical Brain Lab"
    description = "A Neuropsychology Research Lab"
    email = "clinicalbrainlab@gmail.com"
    # phone = ""
    address = "Nanyang Technological University, 48 Nanyang Avenue, Singapore 639818"
    year = 2020
    avatar = "img/logo_CBL.png"
    background = ""
    favicon = "img/favicon.png"
    DateForm = "June, 2020"

    showSubheader = false
    showRecentWorks = true
    showDownload = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

# main menu
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
name = "People"
url = "/people"
weight = 2
hasChildren = true

  [[menu.main]]
  parent = "People"
  name = "Principal Investigator"
  URL = "/people/prof-annabel"
  weight = 1

  [[menu.main]]
  parent = "People"
  name = "Research Scientists and Fellows"
  URL = "/people/research-fellow"
  weight = 2

  [[menu.main]]
  parent = "People"
  name = "Graduate Students"
  URL = "/people/graduate-student"
  weight = 3

  [[menu.main]]
  parent = "People"
  name = "Research Crew"
  URL = "/people/research-crew"
  weight = 4

  [[menu.main]]
  parent = "People"
  name = "Undergraduate Students"
  URL = "/people/undergraduate-student"
  weight = 5

  [[menu.main]]
  parent = "People"
  name = "System Administrators"
  URL = "/people/system-admin"
  weight = 6

[[menu.main]]
name = "Publication"
URL = "/publication"
weight = 3

[[menu.main]]
name = "Blog"
URL = "/blog"
weight = 4

[[menu.main]]
name = "Join Us"
URL = "/join"
weight = 5
hasChildren = true

  [[menu.main]]
  parent = "Join Us"
  name = "Doctorate Research Fellowship"
  URL = "/join/doctoral-fellowships"
  weight = 1

  [[menu.main]]
  parent = "Join Us"
  name = " Post-doctoral Research Fellowships/Research Fellow"
  URL = "/join/post-doctoral"
  weight = 2

  [[menu.main]]
  parent = "Join Us"
  name = "Part-time System Administrator"
  URL = "/join/system-administrator"
  weight = 3

[[menu.main]]
name = "Participate"
URL = "/participate"
weight = 6
  
[[menu.main]]
name = "Contact Us"
URL = "/contact"
weight = 7

[[menu.main]]
name = "Events"
URL = "/events"
weight = 8
hasChildren = true

  [[menu.main]]
  parent = "Events"
  name = "Conferences"
  URL = "/events/conferences"
  weight = 1

  [[menu.main]]
  parent = "Events"
  name = "Visiting Professors"
  URL = "/events/visiting-professors"
  weight = 2

  [[menu.main]]
  parent = "Events"
  name = "Research Visits"
  URL = "/events/research-visits"
  weight = 3

# to sign up later: https://disqus.com/
[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

# to sign up later: https://marketingplatform.google.com/about/analytics/#?modal_active=none
[params.google.analytics]
    trackerID = ""

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/Clinical-Brain-Lab-1025744954121571"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/cblntu"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "github"
	url = "https://github.com/ClinicalBrainLab"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = "github"
[[params.social]]
	title = "email"
	url = "mailto:clinicalbrainlab@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"

